/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hucor
 */
public class CarPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarPanel
     */
    public CarPanel() {
        initComponents();
        //ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lanbo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pricecase = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        DescriptionCase = new javax.swing.JLabel();
        ImageLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pricecase.setText("Price");
        add(Pricecase, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 15, 127, 74));

        jButton1.setText("Rent");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 115, 127, 56));

        DescriptionCase.setText("blabla car");
        add(DescriptionCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 54, 234, 97));

        ImageLabel.setText("jLabel1");
        ImageLabel.setToolTipText("");
        add(ImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 6, 180, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptionCase;
    public javax.swing.JLabel ImageLabel;
    private javax.swing.JTextField Pricecase;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
